### ISSUE TITLE
SPK should allow for Dockerfile to not be in the root directory

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1007]
**As a:** Developer

**I want:** To place my Dockerfile in a location consistent with my project, not assumed to be in the root of the project directory.

**Describe the solution you'd like:** There should be a mechanism (flag, variable group, etc) to inform `az acr build` of the location of a Dockerfile.

**Comment by andrebriggs** [comment]
@jmspring I think this is reasonable. Especially in the case when you are using `spk project init` and `spk service create` on a pre-existing application repository. I think the steps you're mentioning are:

1. `cd` to existing application repo
2. call `spk project init`
3. call `spk service create` with a flag to specify the path to your existing Dockerfile

Another approach could be:
1. `cd` to existing application repo
2. call `spk project init`
3. call `spk service create` and the command will recursively scan for a pre-existing Dockerfile and prompt the user on if they want to use that Docker file.

How does that sound?

Since `spk service create` is something that will be done manually by a user I think providing an interactive experience may help

**Comment by mtarng** [comment]
looks like `az acr build` supports this.

https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#optional-parameters

`--file -f
The relative path of the the docker file to the source code root folder. Default to 'Dockerfile'.`

`spk service create` should supply the path to the Dockerfile, and spk should calculate the relative paths for the service directory and the service's dockerfile and store it in `bedrock.yaml` and modify the build pipeline to include this flag.

Though I don't think this is a priority for now.

@andrebriggs @jmspring @bnookala @evanlouie

**Comment by yradsmikham** [comment]
After discussing with customer, no longer necessary.
