### ISSUE TITLE
SPK Scaffold should fill in defaults 

### ISSUE THREAD

**Issue by jmspring** [microsoft/bedrock#1028]
**As a:** an operator

**I want:** spk scaffold to minimize the number of entries that must be populated

**So that:** I can expedite the deployment of my cluster.

**Describe the solution you'd like:** Many variables have default values, either in the variables.tf or in the modules themselves.  This should be reflected in either pre-populating the value or providing a commented out value such that the user is aware that it is an option.

**Comment by yradsmikham** [comment]
@jmspring default values were removed form `spk scaffold` because it was requested.

https://github.com/microsoft/bedrock/issues/811

**Comment by yradsmikham** [comment]
After discussing, we find that hiding defaults might not be ideal all of the time because users cannot tell which variables are relying on defaults. 

Some proposed solutions:

1. Create a new flag to display default values in definitions.
2. Debug output indicating which are optional 

@jmspring @timfpark

**Comment by andrebriggs** [comment]
@yradsmikham What would a new flag look like?

**Comment by yradsmikham** [comment]
@andrebriggs, it can be some kind of "switch" flag, like `--include-defaults`, which will display defaults in the `definition.yaml`.

**Comment by andrebriggs** [comment]
My take is to just increase the logging as mentioned below 

> 2. Debug output indicating which are optional
