### ISSUE TITLE
Introspection dashboard needs better error handling

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#1066]
**As a:** user 

**I want:** to see meaningful messages on the page and console

**So that:** I can troubleshoot why my dashboard is not setup correctly

**Describe the solution you'd like:**
Right now (and with the upcoming changes to backend) the error handling in introspection dashboard is extremely weak. When there's a failure in backend or in fetching data from APIs, an empty table is shown. 
- [x] Support error handling in dashboard and show meaningful error message, along with console errors about the issue

**Acceptance Criteria:**
Troubleshooting is easier

**Describe alternatives you've considered:**

**Additional context:**

**Does this require updates to documentation?:** No

**Comment by andrebriggs** [comment]
Some things to keep in mind since we have a API in the backend
- HTTP status codes
- Human readable message
- Specific error messages
- Consider having context in the response header

The endpoints we seem to expose on the backend are
- deployments
- clustersync
- author

@samiyaakhtar this might be an epic since we have an API that is really the price that generates errors

**Comment by andrebriggs** [comment]
More examples of where error messages would help below. The shimmer is repeating meanwhile the call to deployments has files (error 503) but there is nothing to let the user know

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/3119513/77993412-f3fc6f00-72dc-11ea-8c8c-261c108f51bb.png">
