### ISSUE TITLE
SPK displays “error” when we have a warning

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#1140]
**Describe the bug:**

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/3119513/76374707-309e0180-6301-11ea-8253-ebc2f6cf0665.png">

This is confusing to users.

## Suggestion

1. Obviously `spk infra scaffold` runs fine with just command line flags. We shouldn't display a warning for this case. I suspect spk command that work without a configuration file might display this message too. We should re-work that logic.
2. Additionally the warning message should remove the word **error** and simply say ` The SPK configuration file found.`
3. **Also** we should only display this warning if verbose mode is activated

**Comment by yradsmikham** [comment]
My concern with some of the suggestions for this issue is that even though `spk infra scaffold` runs successfully without initializing spk, a warning should still be displayed because it informs the user that `spk infra scaffold` _can_ utilize the `spk-config.yaml` to configure infrastructure settings. Additionally, other spk commands rely on this message to inform users, so I think it makes sense that this message is outputted normally every time spk is not initialized.

Instead, maybe we can lower the severity of the message. We can re-word the message to let users know that the spk config file was not found and that we recommend them to run `spk init` or ensure that all argument values are passed in, or something along those lines. If have a "warning" message is misleading for users, we can also convert it to `info`.

@andrebriggs

**Comment by andrebriggs** [comment]
@yradsmikham we need to remove the word "**error**". From what I've seem that is anxiety raising to some folks

> Additionally the warning message should remove the word error and simply say The SPK configuration file found.

I agree with recommending to a user to run `spk init`. Sorry if that didn't come through in suggest #1

**Comment by yradsmikham** [comment]
@andrebriggs Agreed. The word "error" is misleading, and I do intend to remove that.

I guess the point I was trying to make is this should not be displayed only in `verbose` mode, and by "re-working the logic", it can simply mean re-wording the message, as opposed to revising the code.
