### ISSUE TITLE
Instructions on handling errors in Flux installation without re-creating entire cluster

### ISSUE THREAD

**Issue by ghost** [Microsoft/bedrock#136]
During Boulder team Bedrock ramp-up, we encountered an issue where Flux did not install correctly on the cluster, and re-running the terraform commands (which run deply_flux.sh) failed because the flux namespace already existed on the cluster.  Provide instructions for handling this case, or have the script check to see if the namespace already exists and delete if it does.

**Comment by seushermsft** [comment]
Some extra details: 

We initially had the wrong configuration in flux so it wasn't talking to the right GitHub repo. We update the config and re-ran `terraform apply`, which wouldn't re-run deploy_flux.sh since all of the Azure resources were already deployed.  At that point, we manually re-ran deploy_flux.sh, which failed since the `flux` namespace already existed in AKS.

The optimal solution for this would be to replace the `null_resource` named `deploy_flux` with a call to `uuid` so deploy_flux.sh will always re-run when calling `terraform apply`, and before running it, delete the flux namespace via `kubectl delete namespaces flux`.  That would essentially allow updating flux by re-running terraform and won't impact the production service AFAIK.

**Comment by seushermsft** [comment]
In discussing this with Andre, we agree that this work should be:

1. Remove `flux_recreate`
2. Update `deploy_flux.sh` to handle deleting the `flux` namespace if it exists
3. Document using `terraform taint -module="flux" null_resource.deploy_flux` to force the flux step to re-run

**Comment by andrebriggs** [comment]
We have a similar issue [here](https://github.com/Microsoft/bedrock/blob/services/cluster/common/kubediff/deploy_kubediff.sh) with Kubediff. We create a namespace imperatively as well (yet to be merged to master)

cc  @yradsmikham @samiyaakhtar

**Comment by seushermsft** [comment]
@samiyaakhtar @yradsmikham - Making namespace creation idempotent is pretty straightforward. If you want, you can add code similar to this to your script:
```
echo "creating kubernetes namespace $KUBE_NAMESPACE if needed"  
if ! kubectl describe namespace $KUBE_NAMESPACE > /dev/null 2>&1; then  
    if ! kubectl create namespace $KUBE_NAMESPACE; then  
        echo "ERROR: failed to create kubernetes namespace $KUBE_NAMESPACE"  
        exit 1  
    fi   
fi  
```

**Comment by samiyaakhtar** [comment]
@seushermsft Just made a quick PR to update this #148

**Comment by seushermsft** [comment]
@dtzar @jmspring - The original account that created this issue was deleted. Can one of you mark this issue as closed since David merged my PR? My non-existent permissions don't let me.

**Comment by dtzar** [comment]
Done
