### ISSUE TITLE
Allow configuration of sub directories in kubediff and flux deployment

### ISSUE THREAD

**Issue by andrebriggs** [Microsoft/bedrock#161]
Perform implementation from the findings of #149

**Comment by yradsmikham** [comment]
This issue does not cover testing for Kubediff since it is still under development. Only Flux.

Source code changes have been made to the Terraform Flux module and cluster environments.

As noted in chat, frequently running a `terraform apply` to spin up a new AKS cluster that will test the new code changes made to the Flux module has proven to fail. When Terraform fails to build the AKS resource, the following error is shown:

```
* azurerm_kubernetes_cluster.cluster: Error waiting for completion of Managed Kubernetes Cluster "yradsmik-walmart-dev" (Resource Group "yradsmik-walmart-dev"): Code="NotFound" Message="resources.DeploymentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"DeploymentNotFound\" Message=\"Deployment '174ef31d-f6cb-41fb-9d28-921a7163968f' could not be found.\""
```
Some users have reported this issue to be tied with reaching limits/quotas on Azure.

Regardless, after a few iterations, `terraform apply` runs successfully, and Flux logs indicate that the code change is working as expected.

**Comment by yradsmikham** [comment]
https://github.com/Microsoft/bedrock/pull/190
