### ISSUE TITLE
kubediff fails with CrashLoopBackOff

### ISSUE THREAD

**Issue by timfpark** [Microsoft/bedrock#287]
After cluster spin up, kubediff fails in a continuous loop with the error:

```
$ kubectl logs kubediff-6bl67 -n kubediff kubediff
time="2019-04-02T03:17:43Z" level=info msg="Listening on address :80"
time="2019-04-02T03:18:43Z" level=info msg="Running '/kubediff' with argments [/data/repo/ --namespace default]"
time="2019-04-02T03:18:43Z" level=info msg="Command exited successfully"
time="2019-04-02T03:19:43Z" level=info msg="Running '/kubediff' with argments [/data/repo/ --namespace default]"
time="2019-04-02T03:19:43Z" level=info msg="Command exited successfully"
```

Expected:  kubediff starts and starts evaluating diffs versus resource manifests in repo.

**Comment by andrebriggs** [comment]
Closing this issue since Kubediff has been disabled for the moment. 

There are a few issues with kubediff we need to figure out:

- Kubediff uses an [old version](https://github.com/weaveworks/kubediff/pull/79) an `kubectl` gives errors around some valid namespace differences
- Some components on the Cloud Native Stack don't support namespace in their helm charts.
