### ISSUE TITLE
Git PR status waits for Azure Devops Pipeline to return status code on jobs that wont trigger the pipeline.

### ISSUE THREAD

**Issue by NathanielRose** [microsoft/bedrock#408]
When editing files such as README's or .md which are excluded in the `azure-pipeline.yml` git pull request will remain unapproved due to the Build check never being validated. 

![image](https://user-images.githubusercontent.com/8294326/57249587-31d41300-6ffa-11e9-8d6b-0d57c1ecde00.png)

**Comment by NathanielRose** [comment]
@jmspring @andrebriggs Issue referenced here - https://github.com/MicrosoftDocs/vsts-docs/issues/2363

**Comment by andrebriggs** [comment]
@NathanielRose is this still an issue?

**Comment by yradsmikham** [comment]
In order to properly exclude builds from running when `.md` files are updated, we will need to specify the path to the `.md` files explicitly in the `exclude` path of the `azure-pipelines.yaml`.

This seems inefficient, but azdo does not have a way to "wild card" file path filters. See this post for more details: https://stackoverflow.com/questions/55731861/exclude-file-types-in-ci-triggers-on-azure-devops-pipelines-builds

**Comment by andrebriggs** [comment]
@yradsmikham @NathanielRose can we close this issue?

**Comment by yradsmikham** [comment]
@andrebriggs yes, I think we can. We have a separate issue that already mentions an issue regarding excluding markdown files in pipeline validation.

**Comment by pjivers-bom** [comment]
@yradsmikham Could you please post a link to that separate issue.

**Comment by yradsmikham** [comment]
@pjivers-bom It's been a while since we've revisited this issue, and after some digging around, I was not able to find it. If you are having a similar issue, I recommend creating a new ticket. Thanks!
