### ISSUE TITLE
As a developer I would like to see an example of Portworx

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#511]
- [x] Create Fabrikate definition Portworx
- [x] Portworx integrated in to fabrikate Strimzi based Kafka 
- [x] Set up Portworx with Promtheus end points
- [ ] Provide guidance on how to set up snapshots with Portworx

**Comment by NathanielRose** [comment]
(Stable) Expected Performance achieved and the 3 Portworx PVC replicas are all received writes.
- Solution Deployment PR - https://github.com/cnadolny/azure-kafka-kubernetes/pull/17
- Comparison Matrix Doc Update - Portworx-LoadTesting.docx
- Fabrikate Definition PR - https://github.com/microsoft/fabrikate-definitions/pull/23

**Comment by andrebriggs** [comment]
@NathanielRose you mentioned having to create a "new broker" to get Portworx to work with Kafka (even with manual step) ? Can you explain further?

**Comment by NathanielRose** [comment]
@andrebriggs In the provided fabrikate definition manifests, Strimzi targets a [default PVC](https://github.com/sayar/fabrikate-kafka-sample/blob/master/manifests/kafka-cluster.yaml#L36-#lL43) when the cluster is deployed. To work around directly modifying the fab def manifests to target a Portworx PVC, I instruct the user to provision a new statefulset of kafka brokers/zookeeper in strimzi that will use a portworx storage class since portworx is applied to the cluster after creation.

**Comment by NathanielRose** [comment]
Submitted a PR, which refactors portworx, provides installation scripts, and runs testing for fail over and snapshots. [PR #14](https://github.com/sayar/fabrikate-kafka-sample/pull/14)

**Comment by andrebriggs** [comment]
@NathanielRose have snapshot tests moved from unstable to stable?

**Comment by NathanielRose** [comment]
Snapshot has been removed and tabled for 2nd iteration of stateful workload in a multi-cluster scenario. Provided in this PR is a failover test for High Availability and documentation detailing the functionality of the test. [PR#22](https://github.com/sayar/fabrikate-kafka-sample/pull/22)
