### ISSUE TITLE
Improve docs in dashboard

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/bedrock#680]
**As a:** developer/manager

**I want:** to read docs on how to run the dashboard

**So that:** I can introspect my services

**Describe the solution you'd like:**
Currently, docs for the spektate dashboard are not the most up-to-date. Take in feedback from folks who tried running spektate dashboard and improve the docs on how to update pipelines. 

Tasks:

- [x]  Add information about the `spk deployment dashboard` command to the [Service Introspection Doc](https://github.com/CatalystCode/spk/blob/master/docs/service-introspection.md)

- [x] Add information about onboarding to use service introspection tool as part of spk.

**Comment by andrebriggs** [comment]
@samiyaakhtar I'm going to mark this as `not-scoped` because given the solution  you would like to see we should have a some bullets points of specific parts of documentation we want to improve. Right now we don't know when we are "done" on this task. 

Feel free to remove the `not-scoped` label when you think this is ready.
