### ISSUE TITLE
Develop a shell script that will validate components of Azure DevOps Pipeline build.sh

### ISSUE THREAD

**Issue by yradsmikham** [Microsoft/bedrock#69]
1. Refactor build.sh so that it is broken up into functions. That way, the unit test can source build.sh and reference reusable blocks of code from the script for testing.

2. Develop unit test shell script that will specify default environment variables and call functions from build.sh to run for testing. This should be able to run locally and report results.

**Comment by dtzar** [comment]
I recommend converting this to an Azure Terraform module in the public registry and investigate using the standard test tooling framework used for those modules.
i.e. [The compute module](https://github.com/Azure/terraform-azurerm-compute)

**Comment by yradsmikham** [comment]
> I recommend converting this to an Azure Terraform module in the public registry and investigate using the standard test tooling framework used for those modules.
> i.e. [The compute module](https://github.com/Azure/terraform-azurerm-compute)

https://github.com/Azure/terraform-azurerm-compute#test 

Will definitely look into this for future iterations. Thanks!

**Comment by andrebriggs** [comment]
@dtzar I agree that we should be looking to use Terraform and Terratest where applicable. This issue is broadly name "Develop unit testing" but is specifically about one shell script. @yradsmikham can we change the name of this to reflect the specific task associated here? Moreover we should close this issue since it is marked as down.
