### ISSUE TITLE
Spike: Research how to implement branch policies for git repos as part of automation

### ISSUE THREAD

**Issue by samiyaakhtar** [Microsoft/bedrock#70]
Suggest source repo to setup github repo rules that require at least 1 approver and checks to pass before pull request is allowed to merge. 

Investigate the github API which might potentially allow setting these rules with the help of a personal access token. Currently it seems that a password is required to do this via the GUI. [Reference](https://developer.github.com/v3/repos/branches/#add-required-status-checks-contexts-of-protected-branch)

**Comment by andrebriggs** [comment]
@samiyaakhtar This should be expanded to include branch policies in Azure DevOps as well. For instance see [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/create?view=azure-devops-rest-5.0#merge_strategy_policy)

An interesting question is if there is a "template" we can export from ADO and just reuse so that we don't have to piece together a bunch of API calls? I'll see configuring policies is something we can expect from an ADO CLI

**Comment by andrebriggs** [comment]
@samiyaakhtar I found out from @atbagga that the imminent release of azure-devops-cli-extension will have a CLI method for policy creation. it's actually already in master branch [here](https://github.com/Microsoft/azure-devops-cli-extension/blob/master/azure-devops/azext_devops/dev/repos/policy.py). The new release should be available this week. 

@samiyaakhtar let's chat about where to prioritize this task compared with the others

**Comment by yradsmikham** [comment]
@andrebriggs @samiyaakhtar 

As discussed, I think we can add code to the build.sh to verify whether branch policies are enabled. If they are, then proceed with executing fab commands, and if not, attempt to update branch policies, and if that fails, then fail with exit code.

I will create another issue for this since this item is just a spike. Currently will still need to investigate the Azure CLI extension and see its capability as well.

**Comment by andrebriggs** [comment]
@yradsmikham Before we add code to build.sh for this can we have a separate script that does the behaviors you're describing? Specifically enabling and querying branch policies. We can start with Azure DevOps and then implement for GitHub. 

The reason for this is that we can suggest users use this new script in the repository setup process.

I agree a separate issue should be created for this. Let's make this issue then prioritize in planning.

CC @samiyaakhtar
