### ISSUE TITLE
Spike - Environment specification in multistage pipeline

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#724]
**As a:**
Developer 

**I want:**
to specify different deployments in a multistage pipeline.

**So that:**
I can generate different `fabrikate` components based on the environment.

**Describe the solution you'd like:**
Investigate the equivalent way to specify environments in multistage deployments compared to deployments that are multiple pipelines.

**Does this require updates to documentation?:**
Yes

**Comment by andrebriggs** [comment]
@edaena marking as not scoped.  Consider putting all this fine grained tasked related to multi stage in one task if they all are truly small tasks. I was under the impress this was done as part of #705

**Comment by samiyaakhtar** [comment]
@andrebriggs @edaena my understanding is that this is not an investigation but more a discussion for us to have, to understand where the release environment comes from in a multi-stage pipeline. Since there's no pre-approval process, how does a user create a release for `Dev`, `Staging` etc.? 

Once we understand how a release environment is created, supporting it with service introspection should be trivial.

**Comment by andrebriggs** [comment]
@edaena @samiyaakhtar is this still valid? If so let's have the discussion

**Comment by samiyaakhtar** [comment]
@andrebriggs @edaena no longer valid, based on the agreement in the past week that for multi-stage pipelines going forward, environment name should be the branch name (ring = branch name). We can close this out.
