### ISSUE TITLE
Introspection multi-stage shows incorrect status for cancelled stage

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#745]
**Describe the bug:**
spk introspection shows the incorrect status to a deployment if a stage is cancelled

**To Reproduce:**
1. Have a multi-stage pipeline with 2 stages
2. Queue a build
3. Wait for the first stage to successfully complete
4. Cancel the build

**Expected behavior:**
The status for srcToAcr

Seen:
The status for srcToAcr is failed

**Comment by samiyaakhtar** [comment]
In reference to this pipeline: https://dev.azure.com/epicstuff/hellobedrock/_build/results?buildId=7297&view=results

I think the reason it shows failed for the first pipeline is that we don’t have an if condition for the canceled case in the getIcon function. A workaround is to add an icon for canceled status. Although, in the ideal case it should show succeeded for this step, it might be too much overhead if we add a Boolean column in the storage or have them call a different script for multi-stage pipelines.
 
While testing this in the dashboard, when I updated the icon for “Canceled” type, it looks like a feasible workaround. The reason dashboard is not querying the stage API here instead of the overall pipeline status is, we only query the Timelines api when p1 = p2. But in this case, since there’s no p2, we don’t know this was a multi-stage pipeline to fetch the status from a stage. It might be overkill to have to check the timelines API for every deployment if we try to do extra work to handle this. What do you think of the icon workaround?

**Comment by edaena** [comment]
@samiyaakhtar that sounds like a good workaround.
