### ISSUE TITLE
Support for Windows for CI/CD hosts

### ISSUE THREAD

**Issue by dtzar** [microsoft/bedrock#77]
The null resource provisioning requires bash shell.  This should be at least called out in the readme or refactored to support both Windows and Linux.

**Comment by timfpark** [comment]
... or WSL - but you are correct, let's call that out in the docs.

**Comment by paulbouwer** [comment]
The client host and execution environment requirements should definitely be called out across both `bedrock` and `fabrikate`.

I was taking `fabrikate` for a test drive, to explore how all the bits tied together. I downloaded the Windows binary and the [fabrikate-istio](https://github.com/evanlouie/fabrikate-istio/blob/master/component.yaml) component. The pre and post install hooks were executing bash, which doesn't work that well when executed from a PS shell on a Windows machine.

Allowing scripts for pre and post install hooks is very powerful but makes the components non-portable between OSes. Maybe this is perfectly fine to support essentially MacOS/Linux and bash, but I think it should be explicitly called out and fabrikate Windows binaries not released.

You could build and release a docker image for bedrock that negates this whole conversation, since you could control the OS and dependencies like bash. That may provide a lower barrier to entry.

**Comment by dtzar** [comment]
This is possible to make happen - someone will have to take the time to add a "windows" switch and then when this is enabled execute a new equivalent PowerShell script instead of the shell scripts (i.e. kubeconfig to disk, flux, kubediff ATM)

WSL works for me.

**Comment by timfpark** [comment]
Not a goal of the project for the immediate future.
