### ISSUE TITLE
Multiple variable-group workflows

### ISSUE THREAD

**Issue by edaena** [microsoft/bedrock#796]
**Describe the bug:**
There are two ways to create variable groups:
`spk project create-variable-group` and `spk variable-group create`

**Expected behavior:**
One way to create variable groups

**Does this require updates to documentation?:**
Yes

**Comment by edaena** [comment]
@sarath-p what are your thoughts on this?

**Comment by sarath-p** [comment]
Currently. the two commands are supporting two different requirements and use cases. 

1) `spk project create-variable-group` which is easier to use with a fixed set of variables based on arguments

2) `spk variable-group create` is a general one which requires users to specify `n` of number of variables  data in `yaml` format. 

We need to find a sweet sport to merge usability vs. functionality to merge these two commands. 

@andrebriggs and @evanlouie to comment on merging these with a compromise.

**Comment by andrebriggs** [comment]
I do agree that this is odd. The two commands are in two separate topics: `project` and `variable-group`. 

To me the topic is variable groups so I could see merging `spk project create-variable-group` into the `spk variable-group` topic.

**Comment by andrebriggs** [comment]
@sarath-p thought on this?

> I do agree that this is odd. The two commands are in two separate topics: `project` and `variable-group`.
> 
> To me the topic is variable groups so I could see merging `spk project create-variable-group` into the `spk variable-group` topic.

**Comment by sarath-p** [comment]
@andrebriggs - merging is great! We just need to finalize the command parameters since they both use the same backend codebase. Please take a look at existing parameters for both commands at below links. The main difference is project command has fixed number of parameters vs a file input for `spk variable-group`.

`project cvg` parameters:  https://github.com/CatalystCode/spk/blob/master/docs/project-management.md#create-variable-group

`spk variable-group` parameters: https://github.com/CatalystCode/spk/blob/master/docs/variable-group.md#variable-group

cc @evanlouie

**Comment by samiyaakhtar** [comment]
@sarath-p @andrebriggs I just ran into the issue where I was trying to use the wrong command to add variable group for introspection. Is there a reason this is still under `Not-scoped`? Would be nice to merge the functionalities of these commands into a single one.

**Comment by andrebriggs** [comment]
Was just talking about this with @sarath-p. This is not scoped because there didn't seem to be a concrete plan. 

@samiyaakhtar are you looking for a generic way to add key/value pairs to a variable group with `spk`?

> We just need to finalize the command parameters since they both use the same backend codebase. Please take a look at existing parameters for both commands at below links. The main difference is project command has fixed number of parameters vs a file input for spk variable-group.

@sarath-p what exactly needs to be finalized?

**Comment by samiyaakhtar** [comment]
@andrebriggs yes, while working on integration testing I'm finding that it might be beneficial to make this a more generic command. Was there a reason we had closed this down to just the parameters it currently takes in? cc @sarath-p

**Comment by sarath-p** [comment]
Let's discuss the options offline. We can remove this command at least if the Azure Key Vault linking is not a valid use case at the moment and `spk project cvg` satisfies the requirements. 
Thanks!

**Comment by mtarng** [comment]
Just circling back on this. It sounds like we haven't captured a scenario for `spk variable-group create`. 

The work for adding build variables for a service expects an existing variable group with populated variable values before hand. https://github.com/microsoft/bedrock/issues/1006 is this something we should coopt `spk variable-group create` to be used for? Otherwise, we're leaning towards just documenting guidance for creating variable groups through azure cli or the azdo portal.

Thoughts? @sarath-p @andrebriggs @yradsmikham

**Comment by andrebriggs** [comment]
Closing since `variable-group create` has been deprecated.
