### ISSUE TITLE
Intermittent SPK unit test failure related to SPK infra

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/bedrock#935]
**Describe the bug:**
Looks related to callback timeouts:

Example: https://dev.azure.com/epicstuff/bedrock/_build/results?buildId=10722&view=logs&j=b8865196-746b-550b-1739-d024186ee81d&t=e3c38766-386a-50f9-be17-f2fd51922026

```
FAIL src/commands/infra/generate.test.ts (11.943s)
  ● Validate remote git source › Validating that a git source is cloned to .spk/templates

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      355 | 
      356 | describe("Validate remote git source", () => {
    > 357 |   test("Validating that a git source is cloned to .spk/templates", async () => {
          |   ^
      358 |     const mockParentPath = "src/commands/infra/mocks/discovery-service";
      359 |     const mockProjectPath = "src/commands/infra/mocks/discovery-service/west";
      360 |     const sourceConfiguration = validateDefinition(

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.Object.<anonymous>.describe (src/commands/infra/generate.test.ts:357:3)


Test Suites: 1 failed, 37 passed, 38 total
Tests:       1 failed, 358 passed, 359 total
Snapshots:   0 total
```

**Comment by dennisseah** [comment]
We cannot reproduce this problem on own laptop and we are making some guesses. The failing test is calling `generate.validateRemoteSource` function is an async one. In this function, there are a handful of git related async function calls. We suspect that timeout is due to the tardiness in these functions. One way to address problem is to break `generate.validateRemoteSource` into small functions that's having `generate.validateRemoteSource` to call other function in `generate.ts`. In this manner, we have mocked these small (size) functions in the failing test. And then having additional unit tests to test these small functions individually.
