### ISSUE TITLE
[spk] Documentation for ring management

### ISSUE THREAD

**Issue by mtarng** [microsoft/bedrock#975]
For Ring management, we should have some documentation prior to adding features:

### Documentation 
- [x] Define what a ring is
- [x] Describe when to use rings
- [x] Define prerequisite to use deployment rings in `spk` 
- [x] Define how to add a ring
- [x] Define how to remove a ring
- [x] Define how to determine what services have what rings 
- [x] Describe how to validate a service's ringed deployment

**Comment by andrebriggs** [comment]
A good starting point for the definition of header based routing that `spk` offers? 😁
> Rings are routing rules which map user groups to revisions of code. 

Then we need concretely talk about component that is doing the header based routing 
> Traefik is used as the underlying router to implement header-based routing. When a request is received for a certain ring, Traefik will provide the routing to the appropriate backend service. 

Seems like `spk` does the same
> Traefik will default to the production (master) ring if a caller tries to call a service's ring which does not exist.

from https://github.com/microsoft/ring-operator

**Comment by andrebriggs** [comment]
Draft to be updated:

## Why Header Based Routing for Kubernetes applications

Deployments rings are a concepts that have been used within several Microsoft properties for a while. Also known as _flighting_, deployment rings allow us to progressively deploy services to all types of customers – across a range of (header based) users, which in turn enables us to assess and improve the quality of our products through the use of data-driven techniques.

In the DevOps and Kubernetes world this concept is also known as canary deployments. These deployment expose features to selected users in production, to observe and validate before exposing them to all users.

We recommend a well defined deployment ring promotion criteria to determine if and when a Kubernetes application should be promoted from one ring to another.

**Comment by evanlouie** [comment]
First pass: stashing for now

---

## Rings

### What Is a Ring?

The concept of _Deployment Rings_ is an encapsulation of a production-first
DevOps strategy to group your users into cohorts based on the features of your
application your wish to expose to them -- think A/B or canary testing but in a
more formalized matter in which you rollout changes from a smaller ring into a
larger encompassing ring.

Rings formalize around a the idea of having a single of production users and
smaller rings targeting cohorts of the larger ring and potentially even smaller
rings targeting cohorts of those cohorts. This enables the ability to measure
the impact or _Blast Radius_ of the deployed version of the application.

### When Should I Use a Ring?

Rings are useful when you want:

- To be able to test in production.
- Have flexibility in the number of environments/rings available to your system
  at any given time.
- Have a standardized means to promote environments/rings to larger cohorts.

## Bedrock -- Applying Rings To Microservices

Generally speaking, rings are more traditionally applied to monolithic
applications -- Delivering specific versions of a single application to specific
cohorts as needed. When in the context of Kubernetes and microservices, this
becomes a much larger problem to tackle as you need to be able to extend the
concept and deployment of rings to not only a single application, but _sets_ of
applications within your cluster.

### Conceptual mapping to Git branches

Bedrock maps rings to branches in your application git repository. As branches
represent a divergence from your main production code (ie; `master`), they map
to the idea or rings quite cleanly.

### How its implemented in Bedrock

Due to the limitations of the `Service` type in Kubernetes, Bedrock adopts the
usage of edge routers (Traefik2) with header-based routing capabilities to
identify your Ring via a provided header at ingress time. Instead of only
routing to vanilla Kubernetes `Service`s, for every Bedrock `Ring` and `Service`
defined in your cluster, a Kubernetes `Service` is created to expose it (the
Kubernetes service will be called `<service-name>-<ring-name>`). This _Ringed
Service_ is then exposed via a Traefik2 IngressRoute which routes to it when a
request is made to the router for `/<major-version>/<service-name>/` with a
Header of `Ring: <ring-name>`

To recap, lets imagine you have a Traefik2 ingress service in our cluster with
the name `traefik` and we had an _Ringed Service_ to expose called
`foobar-prod`. Instead of making requests to
`foobar-prod.my-namespace.svc.cluster.local` in your cluster, you would instead
make request to `traefik.my-namespace.svc.cluster.local/<major-version>/foobar`
with an HTTP header containing `Ring: prod`. The request would be routed via
Traefik2 to the correct _Ringed Service_ based on the the the service requested
and the `Ring` header -- routing the request to
`foobar-prod.my-namespace.svc.cluster.local` for you.

## Rings & SPK

### Perquisites

[SPK](https://github.com/CatalystCode/spk) is command line tool meant to ease
the adoption of [Bedrock](https://github.com/microsoft/bedrock/) methodologies
and patterns. With SPK, rings are first class citizens and are managed/tracked
alongside your services, enabling quick scaffolding and deployment of your
services to your rings.

SPK itself has some prerequisites to enable the Rings flow:

### Adding a Ring

Adding a ring is based around a single command:
`spk ring add <ring-name> [--isDefault=true|false]`.

This command adds a new ring to your spk project and tracks it in projects
`bedrock.yaml` file. Subsequently, the command walks through every service in
your project and updates their pipeline to monitor the git branch the ring
corresponds to. Making every merge into the ring branch trigger a new
build/deployment of your ring.

### Removing a Ring

Removing a ring does the inverse of [adding](#adding-a-ring):
`spk ring delete <ring-name>`.

This command removes the ring from your `bedrock.yaml` file and walks through
all the services in your project and removing the ring branch from the service
pipeline YAML.

### What Services Have What Rings?

TBD

### Validating the Deployment of My Ringed Service

TBD
